### ISSUE TITLE
Accounting software evaluation & selection

### ISSUE THREAD

**Issue by Preskton** [nivenly/governance#19]
Identify initial accounting package to manage foundation finances.

## Evaluations

- [x] Odoo
- [x] Freshbooks
- [x] Quickbooks
- [x] OpenCollective
- [x] GNUcash
- [ ] (add others as we discover them)

**Comment by Preskton** [comment]
## Odoo

- https://www.odoo.com/
- Free to use one "application" with unlimited users
- Many other applications like inventory management, etc.
- We are looking mostly at the Accounting application

### Observations

- Relatively easy to get started
- Chart of accounts easy to modify/expand
- Could not get vendor bill OCR to work - repeated Python exceptions with every invoice I tried
- Eval on hold while we wait to hear back from support about Python exceptions

Lots of these when trying to OCR any bill:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6252405/229264334-4d4c861c-af86-480f-8103-f6f0b53ae0c4.png">

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1689, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/saas-16.2/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1716, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1913, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 708, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-16.2/addons/web/controllers/dataset.py", line 32, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.2/addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.2/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.2/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/saas-16.2/iap_extract/models/extract_mixin.py", line 163, in check_ocr_status
    record._check_ocr_status()
  File "/home/odoo/src/enterprise/saas-16.2/account_invoice_extract/models/account_invoice.py", line 616, in _check_ocr_status
    self._save_form(ocr_results, force_write=force_write)
  File "/home/odoo/src/enterprise/saas-16.2/account_invoice_extract/models/account_invoice.py", line 653, in _save_form
    payment_ref_ocr = ocr_results['payment_ref']['selected_value']['content'] if 'payment_ref' in ocr_results else ""
TypeError: 'NoneType' object is not subscriptable

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://nivenly.odoo.com/web/assets/203-2297b38/web.assets_backend.min.js:956:163)
    at XMLHttpRequest.<anonymous> (https://nivenly.odoo.com/web/assets/203-2297b38/web.assets_backend.min.js:964:13)
```

### Decision

Original: No, early encounter of frequent bugs does not instill confidence. 👎🏽 

After discussing with their support team (who has been very responsive and helpful), Odoo emerged as a solid platform that balances ease of use (OCR invoices & process) with some deep customization.

**Comment by Preskton** [comment]
## Freshbooks

- https://www.freshbooks.com/
- $55/mo for Accounts Payable
- Android/iOS app

### Observations

- Easy to get started & load vendors
- Chart of accounts somewhat extensible - able to add new categories
- Did not see how to tag specific journal entries by dimension/tags/etc.
- OCR functionality is OK for simple bills, tends to mangle more complex bills like Hetzner or Linode
- E-mail integration for bills
- Bill editor errors on invoice numbers like we get from 1Password like `in_1MMDISHBax7L5HDfUu73H2jx` (maybe too long?)
- ~~Eval on hold while we wait to hear back from support about bugs in bill editor like inability to delete line items~~
  - Found an alternate editor that seems more stable (open the bill -> edit bill vs. the OCR editor)
- API looks solid
- Payments easy to process

**Comment by Preskton** [comment]
## OpenCollective

- https://opencollective.com/
- We are using them actively for donation management and transaction transparency
- Evaluating as a general ledger

### Observations

- Feature functionality not extensive enough to function as a general ledger

### Decision

No for general ledger 👎🏽 (but yes for transparency)

**Comment by Preskton** [comment]
## Quickbooks

- https://www.quickbooks.com
- Industry standard, probably the default most places go with
- $85/mo for "plus" package
- 5 users

### Observations

- Manually turn on multi-currency
- OCR scanning seems to be significantly more accurate than other platforms
- Lots of trouble with Hetzner bill - doesn't seem to want to tag it as EUR

**Comment by Preskton** [comment]
## GNUCash

- https://www.gnucash.org/
- opensource / GNU
- actively maintained

### Observations

- Seems like it has basic features/functionalities we'd need
- No bill OCR
- UX feel/information architecture is visually challenging - so much so that it's not very approachable for newbies
- Seemed to have most configurable account structure/ledger structure - multi-tiered

### Decision

No 👎🏽

**Comment by Preskton** [comment]
We selected Odoo and have been using it for the past several months.
